site_language: de

collections:
  all_pages:
    output: true
    permalink: /:name/index.html
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  sourcemap: always
  style: compressed
kramdown:
  syntax_highlighter_opts:
    disable : true
