site_language: de

collections:
  pages_de:
    output: true
  pages_en:
    output: true
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  sass_dir: _sass
  sourcemap: always
  style: compressed
kramdown:
  syntax_highlighter_opts:
    disable : true
